package com.ipcoding.coachpro.core.util

object TestTags {

    const val BUTTON_CONFIRM_MAINSCREEN = "MAINSCREEN_BUTTON_CONFIRM"
    const val TRAINING_TEXT = "TRAINING_TEXT"
    const val TRAINING_BUTTON = "TRAINING_BUTTON"
    const val LAZY_ROW_SCHEDULESCREEN = "LAZY_ROW_SCHEDULESCREEN"
    const val BUTTON_TRANSFERS_MAINSCREEN = "BUTTON_TRANSFERS_MAINSCREEN"
    const val BUTTON_TABLE_MAINSCREEN = "BUTTON_LEAGUE_MAINSCREEN"
}